apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-job-deployment
  labels:
    app: test-job
spec:
  replicas: 1 # 실행할 컨테이너 개수
  selector:
    matchLabels:
      app: test-job
  template:
    metadata:
      labels:
        app: test-job
    spec:
      imagePullSecrets:
      - name: docker-registry
      containers:
      - name: test-job-container
        image: docker.comes.co.kr/v2/comes/test-job:latest
        ports:
        - containerPort: 5081
        resources:
          limits:
            memory: "512Mi"
          requests:
            memory: "256Mi"
