apiVersion: v1
kind: Service
metadata:
  name: test-job-service
spec:
  type: NodePort # 외부 접속을 위해 NodePort 사용
  selector:
    app: test-job
  ports:
    - protocol: TCP
      port: 5081      # 서비스 내부 포트
      targetPort: 5081 # 컨테이너 포트
      nodePort: 30081  # 윈도우에서 접속할 포트 (30000~32767 사이 설정)
