apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test-job-ingress
  namespace: z-ebdev-app
  annotations:
    # 이미 설치된 nginx 컨트롤러를 사용하겠다는 뜻입니다.
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: eb.comes.co.kr
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: test-job-service # 아까 확인한 서비스 이름
            port:
              number: 5081 # 서비스 내부 포트
